INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10001, 'Rachit', 'Learn SpringBoot', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10002, 'dummy', 'Learn Spring', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10003, 'Rachit', 'Learn SpringMVC', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10004, 'dummy', 'Learn Hibernate & JPA', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10005, 'Rachit', 'Learn Spring Security', CURRENT_DATE, FALSE);

INSERT INTO TODO (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (10006, 'dummy', 'Learn Java REST API', CURRENT_DATE, FALSE);