INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME)
VALUES (10001, 'LEARN AWS', false, CURRENT_DATE(), 'RACHIT');

INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME)
VALUES (10002, 'LEARN SpringBoot', false, CURRENT_DATE(), 'RACHIT');

INSERT INTO TODO (ID, DESCRIPTION, DONE, TARGET_DATE, USERNAME)
VALUES (10003, 'LEARN SpringSecurity', false, CURRENT_DATE(), 'RACHIT');